#:schema node_modules/wrangler/config-schema.json
account_id = "92cb4bb9b2a55d24f5688f2f61864079"

compatibility_flags = ["nodejs_als"]

[[durable_objects.bindings]]
name = "AUTH"
class_name = "AuthDatabaseServer"
script_name = "foreverfamily-server"

[[durable_objects.bindings]]
name = "DB"
class_name = "OrgDatabaseServer"
script_name = "foreverfamily-server"

[[durable_objects.bindings]]
name = "WS"
class_name = "WebsocketServer"
script_name = "foreverfamily-server"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiterServer"
script_name = "foreverfamily-server"

[[kv_namespaces]]
binding = "KV"
id = "86eb734b0be94ef6bd522185e1ef9e42"

[[services]]
binding = "SERVER"
service = "foreverfamily-server"

[[services]]
binding = "IMAGE_PROCESSOR"
service = "image-processor"


# -------------------------------------------------------------------------------------------------
# -------------------------------------- STAGING ENVIRONMENT --------------------------------------
# -------------------------------------------------------------------------------------------------

[env.staging]
name = "foreverfamily-staging"

[[env.staging.durable_objects.bindings]]
name = "AUTH"
class_name = "AuthDatabaseServer"
script_name = "foreverfamily-server-staging"

[[env.staging.durable_objects.bindings]]
name = "DB"
class_name = "OrgDatabaseServer"
script_name = "foreverfamily-server-staging"

[[env.staging.durable_objects.bindings]]
name = "WS"
class_name = "WebsocketServer"
script_name = "foreverfamily-server-staging"

[[env.staging.durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiterServer"
script_name = "foreverfamily-server-staging"

[[env.staging.r2_buckets]]
binding = "R2"
bucket_name = "foreverfamily"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "19098fe743e642bc825b946e11d30a7c"

[[env.staging.services]]
binding = "SERVER"
service = "foreverfamily-server-staging"

[[env.staging.services]]
binding = "IMAGE_PROCESSOR"
service = "image-processor"
