// ---------------------------------------------------------------------------
// Built-in event types
// ---------------------------------------------------------------------------

/** Entity change events — broadcast from server after DB mutations */
export interface EntityChangedMessage {
	event: 'entity:created' | 'entity:updated' | 'entity:deleted';
	entity_type: string;
	id: string | number;
	/** Sparse entity data for create/update; undefined for delete */
	data?: Record<string, unknown>;
	/** The user who triggered the change (if known) */
	user_id?: string;
}

/** Broadcast when a user connects to the WebSocket */
export interface SessionConnectedMessage<
	Meta extends Record<string, unknown> = Record<string, unknown>,
> {
	event: 'session:connected';
	ws_session_id: string;
	num_connections: number;
	meta?: Meta;
}

/** Broadcast when a user disconnects from the WebSocket */
export interface SessionDisconnectedMessage<
	Meta extends Record<string, unknown> = Record<string, unknown>,
> {
	event: 'session:disconnected';
	ws_session_id: string;
	num_connections: number;
	meta?: Meta;
}

/** Sent to a newly connected client with all currently active sessions */
export interface SessionListMessage<
	Meta extends Record<string, unknown> = Record<string, unknown>,
> {
	event: 'session:list';
	sessions: Array<{
		ws_session_id: string;
		meta?: Meta;
	}>;
}

/** Error event sent to an individual connection */
export interface ErrorMessage {
	event: 'error';
	message: string;
	status: number;
}

/** Keep-alive ping (handled automatically by hibernation API) */
export interface PingMessage {
	event: 'ping';
}

/** Keep-alive pong (handled automatically by hibernation API) */
export interface PongMessage {
	event: 'pong';
}

/** Custom event — extensible for app-specific messages */
export interface CustomMessage {
	event: string;
	[key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Union type
// ---------------------------------------------------------------------------

export type WebsocketMessage =
	| EntityChangedMessage
	| SessionConnectedMessage
	| SessionDisconnectedMessage
	| SessionListMessage
	| ErrorMessage
	| PingMessage
	| PongMessage
	| CustomMessage;

// ---------------------------------------------------------------------------
// Session metadata (stored in WS attachment for hibernation recovery)
// ---------------------------------------------------------------------------

/**
 * Default metadata shape when using `@delightstack/auth`.
 * Contains auth-related fields populated by the default `authorize` handler.
 * Custom implementations can define their own metadata type instead.
 */
export type AuthSessionMeta = {
	/** The user's unique ID */
	user_id?: string;
	/** The user's display name */
	user_name?: string;
	/** The user's auth method ID (sub from JWT) */
	user_auth_id?: string;
	/** The user's auth session ID (jti from JWT) */
	user_session_id?: string;
	/** The bitwise encoded permissions for the user (each bit represents a flag of permissions for this room/org) */
	permission?: number;
};

/**
 * Session metadata attached to each WebSocket connection.
 * The `Meta` generic controls the shape of the `meta` field.
 *
 * @typeParam Meta - The metadata shape. Defaults to `AuthSessionMeta` for
 *   apps using `@delightstack/auth`. Pass your own type for custom metadata.
 *
 * @example
 * ```ts
 * // Default (with @delightstack/auth):
 * type Session = WebsocketSessionMeta; // meta?.user_id, meta?.user_name, etc.
 *
 * // Custom metadata:
 * interface MyMeta { role: string; color: string; }
 * type Session = WebsocketSessionMeta<MyMeta>; // meta?.role, meta?.color
 * ```
 */
export interface WebsocketSessionMeta<
	Meta extends Record<string, unknown> = AuthSessionMeta,
> {
	/** Unique ID for this specific WebSocket session (always present, generated by the DO) */
	ws_session_id: string;
	/** The room/org ID this connection belongs to */
	room?: string;
	/** Session metadata — shape depends on the `Meta` type parameter */
	meta?: Meta;
}

// ---------------------------------------------------------------------------
// Session info (client-side presence tracking)
// ---------------------------------------------------------------------------

/** A connected session as seen by the client (used by `WebsocketClient.sessions`) */
export type SessionInfo<Meta extends Record<string, unknown> = Record<string, unknown>> =
	{
		ws_session_id: string;
		meta?: Meta;
	};

// ---------------------------------------------------------------------------
// Client connection status
// ---------------------------------------------------------------------------

export type ConnectionStatus =
	| 'disconnected'
	| 'connecting'
	| 'connected'
	| 'reconnecting';

// ---------------------------------------------------------------------------
// Entity change event (used by DatabaseClient integration)
// ---------------------------------------------------------------------------

export interface EntityChangeEvent {
	type: 'create' | 'update' | 'delete';
	entity_type: string;
	id: string | number;
	data?: Record<string, unknown>;
}
