// ---------------------------------------------------------------------------
// Built-in event types
// ---------------------------------------------------------------------------

/** Entity change events — broadcast from server after DB mutations */
export interface EntityChangedMessage {
	event: 'entity:created' | 'entity:updated' | 'entity:deleted';
	entity_type: string;
	id: string | number;
	/** Sparse entity data for create/update; undefined for delete */
	data?: Record<string, unknown>;
	/** The user who triggered the change (if known) */
	user_id?: string;
}

/** Broadcast when a user connects to the WebSocket */
export interface SessionConnectedMessage {
	event: 'session:connected';
	ws_session_id: string;
	num_connections: number;
	user_id?: string;
	user_name?: string;
	user_auth_id?: string;
	user_session_id?: string;
	meta?: Record<string, unknown>;
}

/** Broadcast when a user disconnects from the WebSocket */
export interface SessionDisconnectedMessage {
	event: 'session:disconnected';
	ws_session_id: string;
	num_connections: number;
	user_id?: string;
	user_name?: string;
	user_auth_id?: string;
	user_session_id?: string;
	meta?: Record<string, unknown>;
}

/** Sent to a newly connected client with all currently active sessions */
export interface SessionListMessage {
	event: 'session:list';
	sessions: Array<{
		ws_session_id: string;
		user_id?: string;
		user_name?: string;
		user_auth_id?: string;
		user_session_id?: string;
		meta?: Record<string, unknown>;
	}>;
}

/** Error event sent to an individual connection */
export interface ErrorMessage {
	event: 'error';
	message: string;
	status: number;
}

/** Keep-alive ping (handled automatically by hibernation API) */
export interface PingMessage {
	event: 'ping';
}

/** Keep-alive pong (handled automatically by hibernation API) */
export interface PongMessage {
	event: 'pong';
}

/** Custom event — extensible for app-specific messages */
export interface CustomMessage {
	event: string;
	[key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Union type
// ---------------------------------------------------------------------------

export type WebsocketMessage =
	| EntityChangedMessage
	| SessionConnectedMessage
	| SessionDisconnectedMessage
	| SessionListMessage
	| ErrorMessage
	| PingMessage
	| PongMessage
	| CustomMessage;

// ---------------------------------------------------------------------------
// Session metadata (stored in WS attachment for hibernation recovery)
// ---------------------------------------------------------------------------

export interface WebsocketSessionMeta {
	/** Unique ID for this specific WebSocket session (always present, generated by the DO) */
	ws_session_id: string;
	/** The user ID */
	user_id?: string;
	/** The user's display name */
	user_name?: string;
	/** The user's auth method ID (sub from JWT) */
	user_auth_id?: string;
	/** The user's auth session ID (jti from JWT) */
	user_session_id?: string;
	/** The room/org ID this connection belongs to */
	room?: string;
	/** Bitwise encoded permission level */
	permission?: number;
	/** Arbitrary app-specific metadata */
	meta?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Client connection status
// ---------------------------------------------------------------------------

export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';

// ---------------------------------------------------------------------------
// Entity change event (used by DatabaseClient integration)
// ---------------------------------------------------------------------------

export interface EntityChangeEvent {
	type: 'create' | 'update' | 'delete';
	entity_type: string;
	id: string | number;
	data?: Record<string, unknown>;
}
